config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    post '/confirm_email' => 'omniauth_callbacks#confirm_email'
  end

  concern :voted do
    member do
      post :vote
      post :unvote
    end
  end

  resources :questions, concerns: :voted do
    resources :comments, defaults: { commentable: 'questions' }
    resources :answers, concerns: :voted do
      put :best, on: :member
    end
    resources :subscriptions, only: [:create, :destroy]
  end

  resources :answers, only: [] do
    resources :comments, defaults: { commentable: 'answers' }
  end

  resources :attachments, only: :destroy

  #post 'search', to: 'search#search'
  match 'search', to: 'search#search', via: :get, as: :search

  namespace :api do
    namespace :v1 do
  resources :profiles, only: :index do
    get :me, on: :collection
  end
  resources :questions, only: [:index, :show, :create] do
    resources :answers, only: [:index, :show, :create], shallow: true
  end
end
end

root to: 'questions#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
  include Votable

  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachable
  belongs_to :user
  has_many  :comments, as: :commentable

  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user

  accepts_nested_attributes_for :attachments

  validates :title, presence: true, length: { in: 5..200 }
  validates :body, presence: true, length: { in: 5..2000 }

  default_scope -> { order('created_at DESC') }
  scope :created_yesterday, -> { where(created_at: Time.zone.now.yesterday.all_day) }

  def subscription_by(user)
    subscriptions.find_by(user: user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
	authorize_resource

	def index
		respond_with Question.all
	end

	def show
		respond_with Question.find(params[:id])
	end

	def create
		respond_with @question = current_resource_owner.questions.create(question_params)
	end

	private

	def question_params
		params.require(:question).permit(:title, :body, attachments_attributes: [:file])
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :build_answer, only: [:show]
  before_action :question_owner, only: [:destroy, :update]
  after_action :publish_question, only: [:create]

  authorize_resource

  respond_to :html
  respond_to :js, only: :destroy
  respond_to :json, only: :create

  include Voted

  def index
    respond_with @questions = Question.all
  end

  def show
    @subscription = @question.subscriptions.find_by user: current_user || Subscription.new
    respond_with @question
  end

  def new
    respond_with @question = Question.new
  end

  def edit
  end

  def create
    respond_with @question = current_user.questions.create(question_params)
  end

  def update
    @question.update(question_params)
    respond_with @questions = Question.all
  end

  def destroy
    respond_with @question.destroy!
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file])
  end

  def build_answer
    @answer = @question.answers.build
  end

  def question_owner
    unless @question.user_id == current_user.id
      render text: 'You do not have permission to modify this question', status: 403
    end
  end

  def publish_question
    PrivatePub.publish_to "/questions", question: @question.to_json if @question.valid?
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_questions.html.slim
- cache collection_cache_key_for :question do
  - @questions.each do |question|
    div id="question-#{question.id}"
      p= link_to question.title, question

      - if user_signed_in? && current_user.id == question.user_id
        p= link_to 'Edit', '', class: 'edit-question-link', data: {question_id: question.id}
        p
          = form_for question, remote: true, html: {id: "edit-question-#{question.id}"} do |f|
            = f.label :title, 'Title'
            = f.text_field :title

            = f.label :body, 'Question'
            = f.text_area :body

            = f.submit 'Save'
        p= link_to 'Delete question', question, method: :delete, remote: true
      br

app/views/questions/destroy.js.erb
$("#question-<%= @question.id %>").remove();

app/views/questions/index.html.slim
- if can?(:create, Question)
  = link_to 'Ask question', new_question_path

br
  .questions
    = render 'questions'

= subscribe_to "/questions"

= render 'templates/question'

app/views/questions/new.html.slim
= nested_form_for @question do |f|
  = f.label :title
  = f.text_field :title
  = f.label :body, 'Text'
  = f.text_area :body

  p Attachments:
  p
    = f.fields_for :attachments, @question.attachments.build do |a|
      = a.label :file
      = a.file_field :file
      = a.link_to_remove "Remove"
    = f.link_to_add 'Add file', :attachments
  = f.submit 'Create'

app/views/questions/show.html.slim
- cache @question do
  div id="question-#{@question.id}" class="question"
    h1= @question.title

    div class="total-votes" = @question.total_votes
    - if user_signed_in? && current_user.id != @question.user_id
      div class="vote"
        - if @question.voted_by?(current_user)
          p= link_to 'Unvote', unvote_question_path(@question), class: 'unvote-link', method: :post, remote: true
        - else
          p= link_to 'Like', vote_question_path(@question, value: 1), class: 'vote-link', method: :post, remote: true
          p= link_to 'Dislike', vote_question_path(@question, value: -1), class: 'vote-link', method: :post, remote: true

    p= render 'subscriptions/subscribe_action_links', question: @question

    p= @question.body

    p Attachments:
    ul class="question-attachments"
      - cache collection_cache_key_for :attachment do
        - @question.attachments.each do |a|
          li id="attachment-#{a.id}"
            = link_to a.file.identifier, a.file.url
            '  -
            - if user_signed_in? && current_user.id == @question.user_id
              = link_to 'remove', a, remote: true, method: :delete


    p= render 'comments/index', resource: @question
    p= render 'comments/form', resource: @question

    h3 Answers
    ul class="answers" data-question-id=@question.id = render @question.answers

    = nested_form_for [@question, @answer], remote: true, data: { type: :json } do |f|
      .answer-errors
      p
        = f.label :body, 'Text'
        = f.text_area :body
      p Attachments:
      p
        = f.fields_for :attachments, @answer.attachments.build do |a|
          = a.label :file
          = a.file_field :file
          = a.link_to_remove "Remove"
        = f.link_to_add 'Add file', :attachments
      = f.submit

  = subscribe_to "/questions/#{@question.id}/answers"
  = subscribe_to "/questions/#{@question.id}/comments"

  = render 'templates/answer'
  = render 'templates/comment'

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  <% @question.errors.full_messages.each do |message| %>
    $('.question-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('.questions').html('<%= j render 'questions' %>');
<% end %>