config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    post '/confirm_email' => 'omniauth_callbacks#confirm_email'
  end

  concern :voted do
    member do
      post :vote
      post :unvote
    end
  end

  resources :questions, concerns: :voted do
    resources :comments, defaults: { commentable: 'questions' }
    resources :answers, concerns: :voted do
      put :best, on: :member
    end
    resources :subscriptions, only: [:create, :destroy]
  end

  resources :answers, only: [] do
    resources :comments, defaults: { commentable: 'answers' }
  end

  resources :attachments, only: :destroy

  #post 'search', to: 'search#search'
  match 'search', to: 'search#search', via: :get, as: :search

  namespace :api do
    namespace :v1 do
  resources :profiles, only: :index do
    get :me, on: :collection
  end
  resources :questions, only: [:index, :show, :create] do
    resources :answers, only: [:index, :show, :create], shallow: true
  end
end
end

root to: 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Votable
  
  belongs_to :question, touch: true
  belongs_to :user
  has_many :attachments, as: :attachable
  has_many :comments, as: :commentable

  after_create :calculate_reputation
  after_create :notify_answer
  after_create :notify_question_subscribers
  before_destroy :rollback_reputation

  accepts_nested_attributes_for :attachments

  validates :body, presence: true, length: { in: 5..2000 }

  default_scope -> { order(best: :desc).order(created_at: :asc) }

  def best!
    answers = question.answers
    answers.each do |a|
      Reputation.calculate(a.user, :best_answer, true)
    end
    answers.update_all(best: false)

    self.update(best: true)
    Reputation.calculate(self.user, :best_answer)
  end

  private

  def calculate_reputation
    Reputation.calculate(self.user, :create_answer)
  end

  def rollback_reputation
    Reputation.calculate(self.user, :create_answer, true)
  end

  def notify_answer
    AuthorMailer.answer(self).deliver_later
  end

  def notify_question_subscribers
    NotifySubscribersJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_question
  before_action :load_answer, only: [:destroy, :update, :best]
  #before_action :answer_owner, only: [:destroy, :update]
  before_action :question_owner, only: [:best]
  after_action :publish_answer, only: :create

  authorize_resource

  respond_to :html, :js

  include Voted

  def create
    respond_with @answer = @question.answers.create(answer_params.merge(user: current_user))
  end

  def update
    @answer.update(answer_params)
    respond_with @answer
  end

  def destroy
    @answer.destroy
    respond_with @answer
  end

  def best
    @answer.best!
    respond_with @answer
  end

  private
  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = @question.answers.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:title, :body, :question_id, :user_id, attachments_attributes: [:id, :file, :_destroy])
  end

  def answer_owner
    unless @answer.user_id == current_user.id
      render text: 'You do not have permission to modify this answer.', status: 403
    end
  end

  def question_owner
    unless @question.user_id == current_user.id
      render text: 'You do not have permission to modify this question', status: 403
    end
  end

  def publish_answer
    PrivatePub.publish_to "/questions/#{@question.id}/answers", answer: @answer.to_json, attachments: @answer.attachments.to_json, total: @answer.total_votes.to_json if @answer.valid?
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
	authorize_resource

	before_action :load_question, except: :show

	def index
		respond_with @question.answers.all
	end

	def show
		respond_with Answer.find(params[:id])
	end

	def create
		@answer = @question.answers.create answer_params.merge(user: current_resource_owner)
		respond_with @question, @answer
	end

	private
	def answer_params
		params.require(:answer).permit(:body)
	end

	def load_question
		@question = Question.find(params[:question_id])
	end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  - cache answer do
    li class="answer_row"
      div id="answer-#{answer.id}" class="answer"
        - if answer.best
          h4= 'This is the best answer!'

        div class="answer-body" = answer.body
        div class="total-votes" = answer.total_votes
        - if user_signed_in? && current_user.id != answer.user_id
          div class="vote"
            - if answer.voted_by?(current_user)
              p= link_to 'Unvote', unvote_question_answer_path(@question.id, answer), class: 'unvote-link', method: :post, remote: true
            - else
              p= link_to 'Like', vote_question_answer_path(@question.id, answer, value: 1), class: 'vote-link', method: :post, remote: true
              p= link_to 'Dislike', vote_question_answer_path(@question.id, answer, value: -1), class: 'vote-link', method: :post, remote: true

        ul class="answer-attachments"
          - answer.attachments.each do |a|
            li id="attachment-#{a.id}"
              = link_to a.file.identifier, a.file.url
              '  -
              - if user_signed_in? && current_user.id == @question.user_id
                = link_to 'remove', a, remote: true, method: :delete
        - if user_signed_in? && current_user.id == answer.user_id
          p= link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }
          p
            = form_for [@question, answer], remote: true, html: { id: "edit-answer-#{answer.id}"} do |f|
              = f.label :body, "Answer"
              = f.text_area :body

              = f.submit 'Save'
          p= link_to 'Delete answer', question_answer_path(@question, answer), method: :delete, remote: true
        - if user_signed_in? && current_user.id == @question.user_id && !answer.best
          p= link_to 'Mark as best answer!', best_question_answer_path(@question, answer), method: :put, remote: true

          p= render 'comments/index', resource: answer
          p= render 'comments/form', resource: answer

app/views/answers/best.js.erb
$('.answers').html('<%= j render @question.answers %>');

app/views/answers/create.js.erb
$('.answer-errors').remove();
<% @answer.errors.full_messages.each do |msg| %>
  $('.answer-errors').before('<p><%= j msg %></p>');
<% end %>

app/views/answers/destroy.js.erb
$('#answer-<%= @answer.id %>').parent("li").remove();

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  answer = $(".answer[id='answer-<%= @answer.id %>']");
  html = $("<%= j render @answer %>");
  answer.html(html.children());
<% end %>