config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    post '/confirm_email' => 'omniauth_callbacks#confirm_email'
  end

  concern :voted do
    member do
      post :vote
      post :unvote
    end
  end

  resources :questions, concerns: :voted do
    resources :comments, defaults: { commentable: 'questions' }
    resources :answers, concerns: :voted do
      put :best, on: :member
    end
    resources :subscriptions, only: [:create, :destroy]
  end

  resources :answers, only: [] do
    resources :comments, defaults: { commentable: 'answers' }
  end

  resources :attachments, only: :destroy

  #post 'search', to: 'search#search'
  match 'search', to: 'search#search', via: :get, as: :search

  namespace :api do
    namespace :v1 do
  resources :profiles, only: :index do
    get :me, on: :collection
  end
  resources :questions, only: [:index, :show, :create] do
    resources :answers, only: [:index, :show, :create], shallow: true
  end
end
end

root to: 'questions#index'

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
	belongs_to :question
	belongs_to :user

	validates :question, presence: true
	validates :user_id, uniqueness: { scope: :question_id }
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
	before_action :authenticate_user!
	before_action :load_question, only: [:create, :destroy]
	before_action :load_subscription, only: :destroy

	authorize_resource
	respond_to :js

	def create
		respond_with(@subscription = @question.subscriptions.create(user: current_user))
	end

	def destroy
		respond_with(@subscription.destroy)
	end

	private
	def load_question
		@question = Question.find(params[:question_id])
	end

	def load_subscription
		@subscription = Subscription.find(params[:id])
	end
end

app/views/subscriptions/_subscribe_action_links.html.slim
.subscription
  - if can?(:create, Subscription) && !question.subscription_by(current_user)
    = link_to 'Subscribe', question_subscriptions_path(question), remote: true, method: :post
  - if can?(:destroy, @subscription) && question.subscription_by(current_user)
    = link_to 'Unsubscribe', question_subscription_path(question, @subscription), method: :delete, remote: true

app/views/subscriptions/create.js.erb
$(".subscription").html("<%= j render 'subscribe_action_links', question: @question %>");

app/views/subscriptions/destroy.js.erb
$(".subscription").html("<%= j render 'subscribe_action_links', question: @question %>");